In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc # 폰트 세팅을 위한 모듈 추가
import koreanize_matplotlib

In [4]:
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [5]:
def getWeighted(name,weightConst):
    forestdf = pd.read_csv(name+'.csv',thousands = ",")
    forestdf.dropna()
    goo = forestdf.columns[0]
    event = forestdf.columns[1]
    forestdf = forestdf.sort_values(by=[goo], axis=0)


    dfsum = forestdf[event].sum()
    forestdf[event] = forestdf[event].apply( lambda x: ((x/dfsum)+1)**weightConst)

    
    return forestdf

In [6]:
def plotDF(df,title):
    names = df[df.columns[0]]
    values = df[df.columns[1]]

    plt.bar(range(16), values, tick_label=names)
    plt.xticks(rotation='vertical')
    plt.savefig('output.pdf',dpi = 1200,bbox_inches='tight')
    plt.title(title)
    plt.show()

In [15]:
gooSub = getWeighted('구군별지하면적',1)
#plotDF(gooSubter,'구군별지하면적')
gooCCTV = getWeighted('재난CCTV',1)
#plotDF(gooSubter,'재난CCTV')
gooFarm = getWeighted('부산 농경지',1)
#plotDF(farm,'부산 농경지')
gooBeach = getWeighted('해안선_원본',1)
gooTree = getWeighted('삼림',1)
gooPeople = getWeighted('통근통학',1)
gooDanger = pd.read_csv('구별위험도.csv')
def concatWeight(df1,df2,posneg):
    if(posneg == 1):
        df1[df1.columns[1]] = df1[df1.columns[1]] *  df2[df2.columns[1]]
    if(posneg == 0):
        df1[df1.columns[1]] = df1[df1.columns[1]] /  df2[df2.columns[1]]
    return df1

concatWeight(gooDanger,gooTree,0)

       구       위험도
0    강서구  1.379171
1    금정구  1.272398
2    기장군  2.372976
3     남구  1.293517
4     동구  1.155086
5    동래구  0.452236
6   부산진구  2.617036
7     북구  2.632049
8    사상구  1.608410
9    사하구  0.696536
10    서구  1.648110
11   수영구  2.847252
12   연제구  1.447523
13   영도구  1.984466
14    중구  0.198586
15  해운대구  2.109225

In [ ]:
gooSubter = getWeighted('',1)
plotDF(gooSubter)

In [ ]:
gooSubter = getWeighted('해안선_원본',1)
plotDF(gooSubter)