In [22]:
import pathlib

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import defaultdict

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

d = defaultdict(LabelEncoder)
print(tf.__version__)

2.13.0

In [23]:
goose = ['금정구','동래구','해운대구','기장군','남구','동구','중구','부산진구','영도구','사상구','사하구','수영구','북구','연제구','강서구']

In [47]:
def small_df(name):
    sdf = pd.read_csv(name+".csv")
    sdf.insert(2, "LandName",name, True)
    return sdf

In [48]:
initial = small_df(goose[0])

for k in goose[1:]:
    initial = pd.concat([initial,small_df(k)], ignore_index=True)
df = initial

In [49]:

replaceDic ={'총강수량(mm)': 'total_rain','강수계속시간(시간)':'rain_duration','최다강수1H':'max_rain',
                   '일강수량(mm)':'daily_rain','누적 강수량(mm)-2일':'culmu_rain_2','누적 강수량(mm)-3일':'culmu_rain_3',
                   '최대풍속(m/s)':'max_wind','평균기온(℃)':'avg_temp','기간(일)':'duration' ,'침수면적(1,000㎡)':'sunk','태풍':'typhoon','피해액(백만원)':'damage'}
df.rename(columns = replaceDic,inplace = True)

In [50]:
blacklist = ['max_rain','max_wind','daily_rain','damage','culmu_rain_2','culmu_rain_3','total_rain']

df[blacklist] = df[blacklist].fillna(0)
df['avg_temp'] = df['avg_temp'].fillna(df['avg_temp'].mean())
df = df.dropna()

In [51]:
df['damage'] =df['damage'].apply(lambda x:float(str(x).replace(",","")))
def classify(num):
    if(num > 600000):
        return 4
    if(100000< num < 500000):
        return 3
    if(50000 < num < 100000):
        return 2
    if(10000 < num < 50000):
        return 1
    return 0
df['damage'] =df['damage'].apply(classify )

C:\Users\master\AppData\Local\Temp\ipykernel_19336\1044137894.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['damage'] =df['damage'].apply(lambda x:float(str(x).replace(",","")))
C:\Users\master\AppData\Local\Temp\ipykernel_19336\1044137894.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['damage'] =df['damage'].apply(classify )

In [52]:
df

,번호,일자,LandName,sunk,damage,total_rain,duration,typhoon,rain_duration,max_rain,daily_rain,culmu_rain_2,culmu_rain_3,max_wind,avg_temp
0,1.0,2006-07-09,금정구,4.7,4,587.5,21.0,없음,24.0,54.0,167.0,207.5,207.5,3.8,23.600000
1,2.0,2006-07-10,금정구,4.7,4,587.5,21.0,에위니아,20.0,70.0,180.0,347.0,387.5,11.4,23.600000
2,3.0,2006-07-11,금정구,4.7,4,587.5,21.0,없음,9.0,1.5,5.0,185.0,352.0,6.7,25.100000
3,4.0,2006-07-12,금정구,4.7,4,587.5,21.0,없음,24.0,4.5,16.0,21.0,201.0,4.8,26.700000
4,5.0,2006-07-13,금정구,4.7,4,587.5,21.0,없음,0.0,0.0,0.0,16.0,21.0,5.8,29.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,127.0,2016-10-04,강서구,101.4,4,70.5,4.0,없음,1.0,1.0,1.0,1.0,1.0,10.0,23.100000
908,128.0,2016-10-05,강서구,101.4,4,70.5,4.0,없음,24.0,28.0,69.5,70.5,70.5,28.9,21.400000
909,129.0,2016-10-06,강서구,101.4,4,70.5,4.0,없음,0.0,0.0,0.0,69.5,70.5,11.6,21.900000
910,130.0,2017-09-11,강서구,4.1,0,0.0,2.0,없음,0.0,0.0,0.0,0.0,0.0,0.0,24.122722
911,131.0,2017-09-12,강서구,4.1,0,0.0,2.0,없음,0.0,0.0,0.0,0.0,0.0,0.0,24.122722

In [53]:
amount_data = ['damage','duration','total_rain','max_wind']

In [54]:
landf = pd.get_dummies(df['LandName'],dtype = int)
typhoondf = pd.get_dummies(df['typhoon'],dtype = int)
my_land =landf.columns.values.tolist()
my_typhoon = typhoondf.columns.values.tolist()
df[my_land] = landf
df[my_typhoon] = typhoondf

C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_land] = landf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf
C:\Users\master\AppData\Local\Temp\ipykernel_19336\74268524.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[my_typhoon] = typhoondf

In [55]:
train_dataset = df[amount_data+my_land+my_typhoon].sample(frac=0.8,random_state=0)
test_dataset = df[amount_data+my_land+my_typhoon].drop(train_dataset.index)
test_dataset

,damage,duration,total_rain,max_wind,강서구,금정구,기장군,남구,동구,동래구,...,해운대구,고니,나비,뎬무,라마순,루사,매미,산바,없음,에위니아
9,4,21.0,587.5,4.3,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,4,21.0,587.5,4.4,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19,4,21.0,587.5,5.5,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23,0,5.0,335.5,3.1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,0,7.0,193.0,7.0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,0,10.0,112.0,11.3,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
882,0,10.0,112.0,8.4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
888,0,10.0,112.0,5.2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
892,0,4.0,0.0,8.2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
895,0,2.0,228.0,9.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [56]:
train_stats = train_dataset.describe()
train_stats.pop("damage")
train_stats = train_stats.transpose()
train_stats

            count        mean         std  min    25%    50%    75%    max
duration    703.0   11.163585    7.512590  1.0    4.0    8.0   21.0   21.0
total_rain  703.0  270.986344  163.743597  0.0  133.0  260.0  386.0  672.5
max_wind    703.0    6.273969    4.081679  0.0    3.9    5.2    8.0   28.9
강서구         703.0    0.147937    0.355291  0.0    0.0    0.0    0.0    1.0
금정구         703.0    0.046942    0.211665  0.0    0.0    0.0    0.0    1.0
기장군         703.0    0.083926    0.277474  0.0    0.0    0.0    0.0    1.0
남구          703.0    0.061166    0.239806  0.0    0.0    0.0    0.0    1.0
동구          703.0    0.075391    0.264209  0.0    0.0    0.0    0.0    1.0
동래구         703.0    0.064011    0.244947  0.0    0.0    0.0    0.0    1.0
부산진구        703.0    0.048364    0.214687  0.0    0.0    0.0    0.0    1.0
북구          703.0    0.072546    0.259575  0.0    0.0    0.0    0.0    1.0
사상구         703.0    0.065434    0.247466  0.0    0.0    0.0    0.0    1.0
사하구         703.0    0.081081    0.273154  0.0    0.0    0.0    0.0    1.0
수영구         703.0    0.007112    0.084094  0.0    0.0    0.0    0.0    1.0
연제구         703.0    0.065434    0.247466  0.0    0.0    0.0    0.0    1.0
영도구         703.0    0.075391    0.264209  0.0    0.0    0.0    0.0    1.0
중구          703.0    0.025605    0.158065  0.0    0.0    0.0    0.0    1.0
해운대구        703.0    0.079659    0.270957  0.0    0.0    0.0    0.0    1.0
고니          703.0    0.008535    0.092055  0.0    0.0    0.0    0.0    1.0
나비          703.0    0.002845    0.053300  0.0    0.0    0.0    0.0    1.0
뎬무          703.0    0.001422    0.037716  0.0    0.0    0.0    0.0    1.0
라마순         703.0    0.001422    0.037716  0.0    0.0    0.0    0.0    1.0
루사          703.0    0.005690    0.075270  0.0    0.0    0.0    0.0    1.0
매미          703.0    0.025605    0.158065  0.0    0.0    0.0    0.0    1.0
산바          703.0    0.002845    0.053300  0.0    0.0    0.0    0.0    1.0
없음          703.0    0.938834    0.239806  0.0    1.0    1.0    1.0    1.0
에위니아        703.0    0.012802    0.112501  0.0    0.0    0.0    0.0    1.0

In [57]:
train_labels = train_dataset.pop('damage')
test_labels = test_dataset.pop('damage')

In [58]:
def norm(x):
  return (x - train_stats['mean']) / train_stats['std']
normed_train_data = norm(train_dataset)
normed_test_data = norm(test_dataset)
normed_train_data

,duration,total_rain,max_wind,강서구,금정구,기장군,남구,동구,동래구,부산진구,...,해운대구,고니,나비,뎬무,라마순,루사,매미,산바,없음,에위니아
328,0.776885,-0.036559,-0.581616,-0.416384,-0.221774,-0.302464,-0.255066,3.499529,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
670,1.309324,1.710074,-0.826613,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
758,0.776885,-0.109845,-0.630615,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
215,0.776885,0.470331,-0.581616,-0.416384,-0.221774,3.301474,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
267,1.309324,0.589419,-0.679615,-0.416384,-0.221774,-0.302464,3.914972,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,-0.687324,-0.067095,-0.287619,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
25,-0.820434,0.393992,-0.214120,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.293990,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
110,0.244445,-0.081141,-0.336618,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,3.396636,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
149,0.776885,-0.219773,-0.508117,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,3.396636,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
152,0.776885,-0.219773,-0.312119,-0.416384,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,3.396636,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797

In [68]:

def build_model():
  model = keras.Sequential([
    layers.Dense(32, activation='relu', input_shape=[len(train_dataset.keys())]),
    layers.Dense(1)
  ])

  optimizer = tf.keras.optimizers.Adam(0.001)

  model.compile("adam", "binary_crossentropy", metrics=["accuracy"])

  return model

In [69]:
model = build_model()

In [74]:
EPOCHS = 1000
class PrintDot(keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs):
    if epoch % 100 == 0: print('')
    print('.', end='')
history = model.fit(
  normed_train_data, train_labels,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[PrintDot()])

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................

In [75]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch

print(hist.round(2))

      loss  accuracy  val_loss  val_accuracy  epoch
0   -15.95      0.16    -15.36          0.11      0
1   -15.95      0.16    -15.36          0.11      1
2   -15.95      0.16    -15.36          0.11      2
3   -15.95      0.16    -15.36          0.11      3
4   -15.95      0.16    -15.36          0.11      4
..     ...       ...       ...           ...    ...
995 -15.95      0.16    -15.36          0.11    995
996 -15.95      0.16    -15.36          0.11    996
997 -15.95      0.16    -15.36          0.11    997
998 -15.95      0.16    -15.36          0.11    998
999 -15.95      0.16    -15.36          0.11    999

[1000 rows x 5 columns]

In [72]:
realnorm=norm(df[amount_data[1:]+my_land+my_typhoon])
realnorm

,duration,total_rain,max_wind,강서구,금정구,기장군,남구,동구,동래구,부산진구,...,해운대구,고니,나비,뎬무,라마순,루사,매미,산바,없음,에위니아
0,1.309324,1.932983,-0.606115,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
1,1.309324,1.932983,1.255863,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,-3.914972,8.775045
2,1.309324,1.932983,0.104376,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
3,1.309324,1.932983,-0.361118,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
4,1.309324,1.932983,-0.116121,-0.416384,4.502683,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,-0.953544,-1.224392,0.912867,2.398212,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
908,-0.953544,-1.224392,5.543314,2.398212,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
909,-0.953544,-1.224392,1.304863,2.398212,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
910,-1.219764,-1.654943,-1.537105,2.398212,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797
911,-1.219764,-1.654943,-1.537105,2.398212,-0.221774,-0.302464,-0.255066,-0.285346,-0.261327,-0.225277,...,-0.29399,-0.092715,-0.053376,-0.037716,-0.037716,-0.075593,-0.161988,-0.053376,0.255066,-0.113797

In [73]:

test_predictions = model.predict(realnorm).flatten()
damagelist = df.loc[test_dataset.index.values.tolist()]['damage']
print(damagelist.max())
for idx,k in enumerate(damagelist):
    print("real=",k,"prediction=",test_predictions[idx])
print(len(test_predictions))

28/28 [==============================] - 0s 3ms/step
4
real= 4 prediction= 1.4974298
real= 4 prediction= 2.6710777
real= 4 prediction= 1.3890904
real= 0 prediction= 1.4664716
real= 0 prediction= 1.4278796
real= 0 prediction= 1.48203
real= 4 prediction= 1.46971
real= 0 prediction= 1.4594978
real= 0 prediction= 1.5026133
real= 0 prediction= 1.48203
real= 0 prediction= 1.4594978
real= 0 prediction= 1.47895
real= 0 prediction= 1.5205914
real= 0 prediction= 1.5103183
real= 0 prediction= 1.533433
real= 0 prediction= 1.553979
real= 0 prediction= 1.4912698
real= 0 prediction= 1.4629847
real= 0 prediction= 1.4912698
real= 0 prediction= 1.4404969
real= 0 prediction= 1.4194677
real= 2 prediction= 1.7708963
real= 2 prediction= 1.7612739
real= 0 prediction= 1.7737641
real= 2 prediction= 1.7727113
real= 2 prediction= 1.7509668
real= 0 prediction= 2.0393202
real= 0 prediction= 1.9596939
real= 3 prediction= 1.9273505
real= 3 prediction= 1.984303
real= 3 prediction= 1.9884559
real= 3 prediction= 1.973439
real= 3 prediction= 1.9648867
real= 0 prediction= 1.9727628
real= 0 prediction= 2.0925086
real= 0 prediction= 2.069346
real= 0 prediction= 1.983487
real= 4 prediction= 2.093774
real= 4 prediction= 2.596909
real= 4 prediction= 2.596909
real= 4 prediction= -0.15315783
real= 4 prediction= -0.17490125
real= 4 prediction= -0.17708817
real= 3 prediction= -0.16669929
real= 3 prediction= -0.10086909
real= 3 prediction= -0.16338176
real= 3 prediction= -0.15009037
real= 3 prediction= -0.10442782
real= 4 prediction= -0.16511595
real= 4 prediction= -0.17107138
real= 4 prediction= -0.15404645
real= 0 prediction= -0.015384398
real= 0 prediction= -0.117592685
real= 3 prediction= 3.3438735
real= 3 prediction= 1.6292678
real= 3 prediction= 1.6281774
real= 3 prediction= 1.6186318
real= 3 prediction= 1.6254407
real= 3 prediction= 1.6292678
real= 3 prediction= 1.629986
real= 4 prediction= 1.6278312
real= 4 prediction= 1.6224844
real= 4 prediction= 1.6206181
real= 0 prediction= 1.6151234
real= 0 prediction= 2.861325
real= 0 prediction= 2.8551345
real= 0 prediction= 6.843422
real= 0 prediction= 6.751491
real= 4 prediction= -0.4133267
real= 0 prediction= 2.8972745
real= 0 prediction= -0.41989538
real= 0 prediction= -0.4082556
real= 0 prediction= -0.40656522
real= 3 prediction= -0.41989538
real= 0 prediction= -0.4209947
real= 1 prediction= -0.4168194
real= 1 prediction= -0.39942047
real= 1 prediction= -0.39942047
real= 1 prediction= -0.38853368
real= 0 prediction= -0.38853368
real= 0 prediction= -0.36072794
real= 0 prediction= -0.4048747
real= 4 prediction= -0.3841792
real= 4 prediction= -0.3534787
real= 4 prediction= -0.39506584
real= 4 prediction= -0.4082556
real= 4 prediction= -0.4048747
real= 4 prediction= -0.41834444
real= 3 prediction= -0.40318444
real= 2 prediction= 1.3837885
real= 0 prediction= 1.3785446
real= 2 prediction= 1.3699837
real= 2 prediction= 1.3944385
real= 2 prediction= 1.3909063
real= 2 prediction= 1.3750126
real= 2 prediction= 2.5518684
real= 2 prediction= 2.5887384
real= 1 prediction= 2.6396942
real= 0 prediction= 2.6331344
real= 0 prediction= 2.614563
real= 3 prediction= 2.6650252
real= 3 prediction= 2.6063147
real= 3 prediction= 3.157125
real= 1 prediction= 3.157125
real= 0 prediction= 2.57891
real= 0 prediction= 2.559836
real= 0 prediction= 6.305706
real= 1 prediction= 6.1075974
real= 1 prediction= 7.117491
real= 1 prediction= 7.2161236
real= 1 prediction= 1.6524329
real= 1 prediction= 1.6570663
real= 4 prediction= 1.6489091
real= 4 prediction= 1.7311358
real= 4 prediction= 1.6829021
real= 0 prediction= 1.6019863
real= 0 prediction= 1.6388206
real= 0 prediction= 1.6289347
real= 4 prediction= 1.6654923
real= 4 prediction= 1.6489091
real= 4 prediction= 1.6698446
real= 0 prediction= 1.4103353
real= 1 prediction= 3.8661623
real= 0 prediction= 1.3372626
real= 4 prediction= 1.3528883
real= 4 prediction= 1.3946679
real= 0 prediction= 1.3842231
real= 0 prediction= 1.3528883
real= 4 prediction= 1.347666
real= 4 prediction= 1.3633331
real= 4 prediction= 1.4312251
real= 4 prediction= 1.4207804
real= 4 prediction= 1.4362781
real= 4 prediction= 1.4412295
real= 3 prediction= 1.3842231
real= 1 prediction= 1.4207804
real= 2 prediction= 1.4758892
real= 0 prediction= 1.4207804
real= 2 prediction= 1.3946679
real= 2 prediction= 1.4103353
real= 2 prediction= 1.3790007
real= 2 prediction= 1.3790007
real= 2 prediction= 1.5152338
real= 2 prediction= 1.507112
real= 2 prediction= 1.5948464
real= 0 prediction= 1.5831656
real= 0 prediction= 1.552872
real= 4 prediction= 1.5831656
real= 2 prediction= 1.5604023
real= 2 prediction= 1.5870593
real= 2 prediction= 1.5454183
real= 2 prediction= 1.5909528
real= 2 prediction= 1.556637
real= 2 prediction= 1.4613008
real= 2 prediction= 1.5125265
real= 2 prediction= 1.467237
real= 3 prediction= 1.5306063
real= 4 prediction= 1.5754626
real= 4 prediction= 1.4881613
real= 4 prediction= 2.0825186
real= 4 prediction= 2.1431947
real= 4 prediction= 1.8332705
real= 0 prediction= 1.7764279
real= 1 prediction= 1.7845515
real= 1 prediction= 1.7769568
real= 1 prediction= 1.7645885
real= 1 prediction= 1.8099508
real= 1 prediction= 2.3335452
real= 0 prediction= 2.2799175
real= 1 prediction= 2.6140013
real= 1 prediction= 2.9298744
real= 0 prediction= 2.9298744
real= 0 prediction= 3.2073894
real= 0 prediction= 3.2090595
real= 0 prediction= 2.0049279
real= 0 prediction= 1.9693031
879