In [5]:
from pandas import DataFrame
import pandas as pd
goodic= {'강서구': 195,
 '금정구': 143,
 '기장군': 265,
 '남구': 140,
 '동구': 123,
 '동래구': 47,
 '부산진구': 271,
 '북구': 271,
 '사상구': 165,
 '사하구': 71,
 '서구': 167,
 '수영구': 288,
 '연제구': 146,
 '영도구': 200,
 '중구': 20,
 '해운대구': 211}

names = list(goodic.keys())
values = list(map(lambda x:x/100,goodic.values()))
data = {'구':names,'위험도':values}
data_df = DataFrame(data) 
data_df.to_csv('구별위험도.csv', index=False, encoding="utf-8-sig")

In [6]:
data_df

       구   위험도
0    강서구  1.95
1    금정구  1.43
2    기장군  2.65
3     남구  1.40
4     동구  1.23
5    동래구  0.47
6   부산진구  2.71
7     북구  2.71
8    사상구  1.65
9    사하구  0.71
10    서구  1.67
11   수영구  2.88
12   연제구  1.46
13   영도구  2.00
14    중구  0.20
15  해운대구  2.11